<?php
/**
 * @author Andrew Nagy
 *
 */

/**
* Class for help
*/
class webrtcphone {

	/*
	* rank (for prioritizing modules)
	*/
	function rank() {

	$rank = 10;
		return $rank;
	}

	/*
	* init
	*/
	function init() {
	}

	/*
	* Adds menu item to nav menu
	*
	* @param $args
	*   Common arguments
	*/
	function navMenu($args) {
		$ari = $_SESSION['ari_user'];
		$settings = webrtc_get_client_settingsByUser($ari['extension']);
		if(!empty($settings)) {
			$html = "<small><small><a href='" . $_SESSION['ARI_ROOT'] . "?m=webrtcphone&f=display'>" . _("WebRTC Phone") . "</a></small></small>";
		} else {
			$html = "";
		}
		return $html;
	}


	/* Displays stats page
	*
	* @param $args
	*   Common arguments
	*/
	
	function display($args) {
		global $amp_conf, $db;
		$ari = $_SESSION['ari_user'];
		$settings = webrtc_get_client_settingsByUser($ari['extension']);
		if(!empty($settings)) {
			$preload = $amp_conf['AMPWEBROOT'].'/recordings/theme/webrtcimages/push';
			if(file_exists($preload)) {
				foreach (glob($preload."/*.png") as $filename) {
				   $html .= '<img id="push_'.basename($filename,'.png').'" src="theme/webrtcimages/push/'.basename($filename).'" style="display:none;">';
				   $html .= '<img id="std_'.basename($filename,'.png').'" src="theme/webrtcimages/'.basename($filename).'" style="display:none;">';
				}
			}
			$html .= '<link rel="stylesheet" href="theme/webrtc.css" type="text/css" />';
			$html .= '<script type="text/javascript" src="theme/js/adaptor.js"></script>';
			$html .= '<script type="text/javascript" src="theme/js/jssip-devel.js"></script>';
			$html .= '<script type="text/javascript" src="theme/js/phone.js"></script>';
			$html .= '<script type="text/javascript" src="theme/js/webrtc.js"></script>';
			$html .= '<form>';
			if(isset($_REQUEST['hidenav'])) {
				$html .= '<script type="text/javascript">removeNav();</script>';
				$pop_pos = 140;
			} else {
				$pop_pos = 154+140;
			}
			$html .= '<input type="hidden" id="realm" name="realm" value="'.$settings['realm'].'">';
			$html .= '<input type="hidden" id="impi" name="impi" value="'.$settings['username'].'">';
			$html .= '<input type="hidden" id="impu" name="impu" value="'.$settings['sipuri'].'">';
			$html .= '<input type="hidden" id="password" name="password" value="'.$settings['password'].'">';
			$html .= '<input type="hidden" id="display_name" name="display_name" value="'.$settings['cid'].'">';
			$html .= '<input type="hidden" id="websocket_proxy_url" name="websocket_proxy_url" value="'.$settings['websocket'].'">';
			$html .= '<input type="hidden" name="enable_rtcweb_breaker" value="false">';
			$html .= '</form>';
			$html .= '<h1>'._("FreePBX WebRTC Phone").'</h1>';
			$webphone .= <<<EOF
<table id="webrtcphone" width="670" height="544" border="0" align="center" cellpadding="0" cellspacing="0" background="theme/webrtcimages/phone-bg3.png">
<tr>
	<td colspan="3" height="5"></td>
</tr>
<tr>
	<td align="center" valign="bottom">
		<table width="425" height="237" border="0" cellspacing="0" cellpadding="0">
			<tr>
				<td width="196" rowspan="3" valign="top">
					<img id="dtmf1" data-audio="dtmf1" data-file="key1" class="webrtcbutton" src="theme/webrtcimages/key1.png" width="55" height="55" /><img id="dtmf2" data-audio="dtmf2" data-file="key2" class="webrtcbutton" src="theme/webrtcimages/key2.png" width="55" height="55" hspace="15" /><img id="dtmf3" data-audio="dtmf3" data-file="key3" class="webrtcbutton" src="theme/webrtcimages/key3.png" width="55" height="55" />
					<img id="dtmf4" data-audio="dtmf4" data-file="key4" class="webrtcbutton" src="theme/webrtcimages/key4.png" width="55" height="55" vspace="4" /><img id="dtmf5" data-audio="dtmf5" data-file="key5" class="webrtcbutton" src="theme/webrtcimages/key5.png" width="55" height="55" hspace="15" vspace="4" /><img id="dtmf6" data-audio="dtmf6" data-file="key6" class="webrtcbutton" src="theme/webrtcimages/key6.png" width="55" height="55" vspace="4" />
					<img id="dtmf7" data-audio="dtmf7" data-file="key7" class="webrtcbutton" src="theme/webrtcimages/key7.png" width="55" height="55" /><img id="dtmf8" data-audio="dtmf8" data-file="key8" class="webrtcbutton" src="theme/webrtcimages/key8.png" width="55" height="55" hspace="15" /><img id="dtmf9" data-audio="dtmf9" data-file="key9" class="webrtcbutton" src="theme/webrtcimages/key9.png" width="55" height="55" />
					<img id="dtmf_s" data-audio="dtmf_s" data-file="key-asterisk" class="webrtcbutton" src="theme/webrtcimages/key-asterisk.png" width="55" height="55" vspace="4" /><img id="dtmf0" data-audio="dtmf0" data-file="key0" class="webrtcbutton" src="theme/webrtcimages/key0.png" width="55" height="55" hspace="15" vspace="4" /><img id="dtmf_p" data-audio="dtmf_p" data-file="key-pound" class="webrtcbutton" src="theme/webrtcimages/key-pound.png" width="55" height="55" vspace="4" />
				</td>
				<td width="39" rowspan="3">&nbsp;</td>
				<td width="180" height="45" valign="top" background="theme/webrtcimages/text-box.png" style="max-width:180px;overflow:hidden;">
					<div style="padding:10px;font-size:60%;white-space:nowrap;max-width:190px"><div style="overflow-x:none;max-width:190px" id="lcd_1"></div><div style="overflow-x:none;max-width:190px" id="lcd_2"></div></div>
				</td>
			</tr>
			<tr>
				<td valign="top" height="7">
					<div id="calleridpop" style="position:absolute;top:118.5px;left:{$pop_pos}px;background-image:url('theme/webrtcimages/incoming-call-bg.png');background-repeat:no-repeat;display:none">
						<!--<div id="calleridname" style="position:relative;top:20px;left:110px;color:white;font-size:150%"></div>-->
						<div width="4" id="calleridnum" style="position:relative;top:35px;left:-140px;color:white;font-size:150%;text-align:center">word</div>
						<img data-audio="answer" data-file="answer-btn2" class="webrtcbutton" style="position:relative;top:-55px;left:30px" src="theme/webrtcimages/answer-btn2.png"/>
						<img data-audio="ignore" data-file="ignore-btn" class="webrtcbutton" style="position:relative;top:-55px;left:70px" src="theme/webrtcimages/ignore-btn.png"/>
						<img src="theme/webrtcimages/incoming-call-bg.png" style="visibility:hidden"/>
						</div>
				</td>
			</tr>
			<tr>
				<td align="right" valign="top"><img id="answer" data-audio="answer" data-file="answer-btn" class="webrtcbutton"  src="theme/webrtcimages/answer-btn.png" align="left" /><img data-audio="hangup" data-file="hangup-btn" class="webrtcbutton" src="theme/webrtcimages/hangup-btn.png" /><br />
					<img data-audio="hold" class="webrtcbutton disabledbutton" data-file="hold-btn" src="theme/webrtcimages/hold-btn.png" align="left" /><img data-audio="mute" data-file="mute-btn" class="webrtcbutton"  src="theme/webrtcimages/mute-btn.png" /><br />
					<img data-audio="transfer" class="webrtcbutton disabledbutton" data-file="transfer-btn" src="theme/webrtcimages/transfer-btn.png" align="left" /><img id="voldwn" data-audio="voldwn" data-file="vol-dwn-btn" class="webrtcbutton" src="theme/webrtcimages/vol-dwn-btn.png" /><br />
					<img data-audio="conference" class="webrtcbutton disabledbutton" data-file="conf-btn" src="theme/webrtcimages/conf-btn.png" align="left" /><img id="volup" data-audio="volup" data-file="vol-up-btn" class="webrtcbutton" src="theme/webrtcimages/vol-up-btn.png" />
				</td>
			</tr>
		</table>
		<br />
		<table width="125" height="140" border="0" align="center" cellpadding="0" cellspacing="0">
			<tr>
				<td align="center" valign="middle"><img src="theme/webrtcimages/message-btn.png" width="108" height="110" /></td>
			</tr>
		</table>
		<table width="670" height="48" border="0" align="center" cellpadding="0" cellspacing="0">
			<tr>
				<td>&nbsp;</td>
			</tr>
		</table>
	</td>
</tr>
</table>
<div id="message"></div>
EOF;
$html .= $webphone;

if(!isset($_REQUEST['hidenav'])) {
	$html .= '<table width="670" id="removeNavLink"><tr><td><center><a style="cursor:pointer" onclick="popoutphone()">'._("Detach Phone From Window").'</a></center></td></td></table>';
}
$html .= <<<EOF
<audio id="audio_remote" autoplay="autoplay" />
<audio id="ringtone"> 
<source src="theme/webrtcsounds/ring.mp3" type="audio/mpeg">
</audio>
<audio id="adtmf1"> 
<source src="theme/webrtcsounds/dtmf1.mp3" type="audio/mpeg">
</audio>
<audio id="adtmf2">
<source src="theme/webrtcsounds/dtmf2.mp3" type="audio/mpeg">
</audio>
<audio id="adtmf3">
<source src="theme/webrtcsounds/dtmf3.mp3" type="audio/mpeg">
</audio>
<audio id="adtmf4">
<source src="theme/webrtcsounds/dtmf4.mp3" type="audio/mpeg">
</audio>
<audio id="adtmf5">
<source src="theme/webrtcsounds/dtmf5.mp3" type="audio/mpeg">
</audio>
<audio id="adtmf6">
<source src="theme/webrtcsounds/dtmf6.mp3" type="audio/mpeg">
</audio>
<audio id="adtmf7">
<source src="theme/webrtcsounds/dtmf7.mp3" type="audio/mpeg">
</audio>
<audio id="adtmf8">
<source src="theme/webrtcsounds/dtmf8.mp3" type="audio/mpeg">
</audio>
<audio id="adtmf9">
<source src="theme/webrtcsounds/dtmf9.mp3" type="audio/mpeg">
</audio>
<audio id="adtmf0">
<source src="theme/webrtcsounds/dtmf0.mp3" type="audio/mpeg">
</audio>
<audio id="adtmf_s">
<source src="theme/webrtcsounds/dtmf_s.mp3" type="audio/mpeg">
</audio>
<audio id="adtmf_p">
<source src="theme/webrtcsounds/dtmf_p.mp3" type="audio/mpeg">
</audio>
EOF;
		} else {
			$html = _('WebRTC Phone has not been configured for your extension');
		}
		return $html;
	}
}